### ISSUE TITLE
Generate $id in the schemas

### ISSUE THREAD

**Issue by davidbarreto** [mbknor/mbknor-jackson-jsonSchema#112]
Hi folks!

I'm working in a project that generate JSON-Schemas from JAXB generated classes (that classes were generated from XSDs). So, I cannot change that classes. The XSDs describe some complex types with the same name and different content (in different XSDs). For that complex types, JAXB generates classes with same name, but package separated, based on XSD namespace. My JSON-Schemas are being generated one JSON-Schema per XDS (with inline definitions). Is there a way to put in that schemas, a kind of namespace? Maybe with $id? I want to avoid a possible name conflict in future codegen through my JSON-Schemas.

Thanks in advance!
David.

**Comment by mbknor** [comment]
Are you generating jsonSchema using **mbknor-jackson-jsonSchema** ? 
If yes, please provide simple example-pojos with generated schema, and sugestions about how you would like the schema to look like.

As of today the jsonSchema generated by mbknor-jackson-jsonSchema does not include/use id/$id but if you convince me, maybe I'll have a look at it.

**Comment by tsjensen** [comment]
The [Spec](http://json-schema.org/understanding-json-schema/basics.html#declaring-a-unique-identifier) says every schema should have a `$id`.

Is there a workaround by which I can get it added to the generated schema?

**Comment by tsjensen** [comment]
It seems one can inject a `$id` by adding this to the top POJO:
```java
@JsonSchemaInject(strings = {
    @JsonSchemaString(path = "$id",
        value = "https://host.example.com/some/url/v1.0.0/my-schema.json")
})
```

**Comment by mdedetrich** [comment]
@mbknor Would it be possible to re-open this ticket? As stated before having the `$id` field is mandatory as part of the JSON spec and the specification for this feature would basically be what @tsjensen suggested here https://github.com/mbknor/mbknor-jackson-jsonSchema/issues/112#issuecomment-646147031

In other words there just needs to be an annotation (lets say `@JsonSchemaId(id = "https://host.example.com/some/url/v1.0.0/my-schema.json"`) which behaves as described above.

There might be an argument to however properly specify this because as part of JSON schema, `$ref`'s point to `$id`'s which is used when JSON schema's reference other JSON schema's.
