### ISSUE TITLE
Properties in object constructor are required.

### ISSUE THREAD

**Issue by mbap** [mbknor/mbknor-jackson-jsonSchema#58]
JSON object properties which are not required are being set as required when setting those values in that objects constructor.

```java
public class Example {
    public Example() {
        field1 = 4;
    }
    @JsonPropertyDescription("asdsad")
    private Object field1;
    
    @JsonPropertyDescription("asdsad")
    private Object field2;
}
```

Then in my schema I see:

```
"required" : [ "field1"],
```
This is trouble for me since I never specified.
```java
@JsonProperty(required=true)
```
and even when I say
```java
@JsonProperty(required=false)
```
it shows up as required anyway.

**Comment by mbknor** [comment]
hmm... that sounds strange.

Maybe you can try to override it using @JsonSchemaInject

**Comment by mbap** [comment]
Ok, I can give that a try. My only worry is that its a bit hacky hah, kinda defeats the purpose of having `@JsonProperty(required=true)`. I will take a look at the source when I get a change to see if I spot anything that could be doing it. Otherwise I may just have to remove those constructors.

**Comment by kog** [comment]
@mbap - are the actual types for your `field1` and `field2` primitive types (IE: int)? I wasn't able to reproduce required attributes with the class you list above, instead I get a schema that looks like:

```
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "Example",
  "type" : "object",
  "additionalProperties" : false,
  "properties" : {
    "field1" : {
      "propertyOrder" : 1,
      "description" : "asdsad",
      "title" : "Field 1"
    },
    "field2" : {
      "propertyOrder" : 2,
      "description" : "asdsad",
      "title" : "Field 2"
    }
  }
}
```

which is what I'd expect from the code that does this: https://github.com/mbknor/mbknor-jackson-jsonSchema/blob/7a4ebe9e91431f69f371749d11889e42d1247095/src/main/scala/com/kjetland/jackson/jsonSchema/JsonSchemaGenerator.scala#L868-L878.

When I swap those types to `int` - which would make sense given your constructor setting `field1` to `4` - I do get a required field. This seems to be logically consistent since primitive types are not nullable.

Here's a diff for what I used to run the test (renamed to `.txt` to deal with GH uploads):
[GH58.patch.txt](https://github.com/mbknor/mbknor-jackson-jsonSchema/files/1618013/GH58.patch.txt)

**Comment by mbap** [comment]
Sorry, yes they are primitive. That was a total oversight on my part apologies. I suppose one solution I can try is to use primative object wrapper classes.

Haven't had much time for testing this but I will try asap. Thanks again for the responses.

**Comment by mbknor** [comment]
Thanks @kog for spotting thing explanation.

@mbap: Since you are using Jackson and Java with primitives, your code cannot know if field1 (int) was set to "0" in json or if it was not included in json at all.
If you need that sort of info, then field1 must be Integer.
It makes no point in setting a field 'not required', if your code cannot know if you got it or not.

**Comment by mbap** [comment]
Awesome thanks for the clear explanation.
