### ISSUE TITLE
All primitive types are marked as "required" in Schema regardless of JsonProperty(required=false} is set

### ISSUE THREAD

**Issue by ctippin** [mbknor/mbknor-jackson-jsonSchema#72]
Given the following simple code:

```
public class JsonSchemaCreator {

  public static void main(String[] args) throws JsonProcessingException {
    ObjectMapper objectMapper = new ObjectMapper();
    JsonSchemaGenerator jsonSchemaGenerator = new JsonSchemaGenerator(objectMapper);
    JsonNode jsonSchema = jsonSchemaGenerator.generateJsonSchema(Foo.class);
    String jsonSchemaAsString = objectMapper.writeValueAsString(jsonSchema);
    System.out.println(jsonSchemaAsString);
  }

  public static class Foo {
    public Foo() {}

    @JsonProperty()
    private String string1;
    @JsonProperty(required = false)
    private int int1 = 0;
    @JsonProperty()
    private boolean bool1;
  }

```
The following output is created:
```
{"$schema":"http://json-schema.org/draft-04/schema#","title":"Foo","type":"object","additionalProperties":false,"properties":{"string1":{"type":"string"},"int1":{"type":"integer"},"bool1":{"type":"boolean"}},"required":["int1","bool1"]}
```
As you can see, both of the primitive fields "int1" and "bool1" are marked as required.  

I found the following in the Scala source, which makes it look like this behavior is by design?  I would expect the JsonProperty(required=true/false) to be honored.  Any feedback or workaround would be appreciated. 

```
// Check if we should set this property as required. Primitive types MUST have a value, as does anything
// with a @JsonProperty that has "required" set to true. Lastly, various javax.validation annotations also
// make this required.

val requiredProperty:Boolean = if (propertyType.getRawClass.isPrimitive || jsonPropertyRequired || validationAnnotationRequired(prop)) {
       true
  } else {
       false
  }
```

Any feedback or workaround would be appreciated. 

Thanks

**Comment by mbknor** [comment]
Hi,

It is like this "by design".

A primitive cannot NOT hold a value.

In your code, the property ** int1** will end up with the value **0**, if your exclude it from the json.

If you would like to allow NOT having a value, you should use **Integer** (with a capital **I**) instead. Then it will end up with **null**, if the value is missing. Or you could use Optional (java) or Option (Scala).

I hope this helps.

**Comment by ctippin** [comment]
Ah I see,  it is a marshalling concern, which  makes sense.  Thanks for the quick response.

**Comment by almson** [comment]
@mbknor You're mistaken. "required" is not about what the Java code is doing, it's about what we expect from input and output documents. Jackson allows various patterns using setters, default values, tracking whether a field has been set, etc. (In particular I'm using `@Jacksonized @Builder` which exposes the setter pattern and default values.)

A setter which takes a primitive value is not required! I'm annoyed by this as well.

I think the real crux of the issue is serialization-vs-deserialization. A primitive field is "required" on serialization since it's always set. However, I'm using this library only to generate schemas for deserialization. This issue crops up in multiple other places, like how this library generates schema based on the class's serializable properties instead of the deserializable properties (ie, those in the Creator method).

**Comment by almson** [comment]
I don't want the schema generator to guess what is or isn't required. It should just follow `JsonProperty(required)`.
