### ISSUE TITLE
JsonTypeInfo.Id.MINIMAL_CLASS does not generate minimal class name

### ISSUE THREAD

**Issue by kermit-the-frog** [mbknor/mbknor-jackson-jsonSchema#78]
Hi,

JsonTypeInfo.Id.MINIMAL_CLASS does not generate minimal class name. Instead it returns the very same class name as JsonTypeInfo.Id.CLASS.

Kind regards
kermit-the-frog

**Comment by mbknor** [comment]
Included in version 1.0.31 which is just released

**Comment by luqasn** [comment]
This does not work for nested classes though :(

It produces `.InnerClassName` instead of the correct (wrt Jackson) `.OuterClassName$InnerClassName`. This is because Jackson uses the package bath of the parent class and strips it from the child class full name instead of taking the `simpleName`:
```
String n = value.getClass().getName();
        if (n.startsWith(_basePackagePrefix)) {
            // note: we will leave the leading dot in there
            return n.substring(_basePackagePrefix.length()-1);
        }
```
See https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/jsontype/impl/MinimalClassNameIdResolver.java#L48

**Comment by mbknor** [comment]
Please open new ticket and feel free to produce PR
