### ISSUE TITLE
generateJsonSchema(Pojo1.class, Pojo2.class)

### ISSUE THREAD

**Issue by dherges** [mbknor/mbknor-jackson-jsonSchema#84]
I have multiple POJos that reference each other.

Would it be possible to support giving multiple classes to generateJsoNSchema()? 

```java
class Pojo1 {
  public Pojo2 member;
  public String foo;
}

class Pojo2 {
  public String bar;
}
```

---

```java
jsonSchemaGenerator.generateJsonSchema(Pojo1 .class, Pojo2 .class);
```

???

**Comment by dherges** [comment]
I should have better demonstrated my use case. I have a colleciton of domain classes. Some have relationships, other's don't. Example:

 - `Pojo1` -> `Pojo2`
 - `Pojo2`
 - `Pojo3` -> `Pojo2`

Now, if I generate the schema for all 3, I get a duplicated schema for `Pojo2`.

I could add a "virtual" holder of the domain world:

 - `Domain` -> `Pojo1`, `Pojo2`, `Pojo3`

and then `generateJsonSchema(Domain.class)` would give me a json schema for all domain classes and w/o duplications.

**Comment by AlexBroadbent** [comment]
Ah okay, I am no expert on the matter - but I suppose it depends what you are using the schema for exactly.

If you are just passing the domain around then a holder would make a lot more sense, as this would contain a definition per object - rather than having to pass around an entire schema per object.

Try wrapping them into a `Domain`, as you suggested, and see if it works for what you are trying to do?

**Comment by mbknor** [comment]
@AlexBroadbent is correct.

You need the "virtual" top domain-class which has pojo1, pojo2 and pojo3 as subTypes to be able to tell jackson ObjectMapper that you would like to parse the jsonString into on of the types.
